global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'product-microservice'
    metrics_path: '/actuator/products/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Product Microservice'

  - job_name: 'orders-microservice'
    metrics_path: '/actuator/orders/prometheus'
    static_configs:
        - targets: [ 'host.docker.internal:8080' ]
          labels:
            application: 'Orders Microservice'

  - job_name: 'inventory-microservice'
    metrics_path: '/actuator/inventory/prometheus'
    static_configs:
        - targets: [ 'host.docker.internal:8080' ]
          labels:
            application: 'Inventory Microservice'